version: "3.0"

services:
  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/env/mysql_credentials
      - ./mysql/env/tz
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
